### PR TITLE
Began updating README and CHANGELOG

### PR DESCRIPTION
**Pull request by jdantonio**
## Do Not Merge

Work in progress. Updating README and CHANGELOG for the v0.9.0 release.

### CODE REVIEW

**Comment by pitr-ch** [comment]
@jdantonio Can I rebase and push -f including my commit on top, for now it's in https://github.com/pitr-ch/concurrent-ruby/tree/readme-changelog

**Comment by jdantonio** [comment]
:+1:

**Comment by jdantonio** [comment]
Please feel free to force push.

**Comment by pitr-ch** [comment]
done

**Pull request merged**
