### PR TITLE
Fixes/improvements to promises.in.md.

### PR DESCRIPTION
**Pull request by keithrbennett**
Great documentation, thank you!

I noticed some things that I thought were unintended, and "fixed" them. ;)

### CODE REVIEW

**Comment by chrisseaton** [comment]
Does anyone have a clue why we'd have written `#` at the end of these lines like this? Must have been some reason...

**Comment by chrisseaton** [comment]
These `#` are definitely supposed to be doing something - they're stripped when the file is processed but I have no idea why.

**Comment by pitr-ch** [comment]
If I remember correctly. They tell the tool not to add the value of the expression at the end as it does for all the other lines.

**Comment by keithrbennett** [comment]
@pitr-ch What tool is that?

**Comment by pitr-ch** [comment]
It uses https://github.com/pitr-ch/md-ruby-eval as far as I remember.

**Comment by chrisseaton** [comment]
Closed based on explanation. Thanks for the thought, though.

**Pull request closed without merging**
