### PR TITLE
Remove ``` from LICENSE.md

### PR DESCRIPTION
**Pull request by mikrobi**
The leading ``` make it hard for [licensed](https://github.com/github/licensed/) to parse the license. Can we drop them?

### CODE REVIEW

**Comment by adamruzicka** [comment]
To expand on this, does the license need to be a markdown file?

**Comment by LikeLakers2** [comment]
If the intent is to have it detected as the MIT License, I believe there is more you'd have to fix with the license file. While it does include the MIT license text, it also includes a link and extra text on the copyright line, which may also be part of why licensed is confused. Additionally, if you look at the fork's repository page, GitHub still shows a generic "View License" link -- suggesting that licensed is still confused about which license the repository is under.

@adamruzicka I've seen some repositories that will use no extension, some that will use .MD, and a couple that even use .TXT. As far as I'm aware, the file extension does not matter -- it only matters that the filename is the case-insensitive name `LICENSE`. Once that is met, GitHub will have licensed parse the file and see if it matches a known license.

**Comment by mikrobi** [comment]
I assume `licensed` reads the license from the [gemspec](https://github.com/ruby-concurrency/concurrent-ruby/blob/7dc6eb04142f008ffa79a59c125669c6fcbb85a8/concurrent-ruby.gemspec#L22) file, which also contains a reference to the `LICENSE.md` file. I don't think the license is actually parsed `LICENSE.md` however the result cached by `licensed` looked weird:


```
summary: Modern concurrency tools for Ruby. Inspired by Erlang, Clojure, Scala, Haskell,
  F#, C#, Java, and classic concurrency patterns.
homepage: http://www.concurrent-ruby.com
license: other
licenses:
- sources: LICENSE.md
  text: "```\nCopyright (c) Jerry D'Antonio -- released under the MIT license.\n\nhttp://www.opensource.org/licenses/mit-license.php
    \ \n\nPermission is hereby granted, free of charge, to any person obtaining a
    copy  \nof this software and associated documentation files (the \"Software\"),
    to deal  \nin the Software without restriction, including without limitation the
    rights  \nto use, copy, modify, merge, publish, distribute, sublicense, and/or
    sell  \ncopies of the Software, and to permit persons to whom the Software is
    \ \nfurnished to do so, subject to the following conditions:  \n \nThe above copyright
    notice and this permission notice shall be included in  \nall copies or substantial
    portions of the Software.  \n \nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY
    OF ANY KIND, EXPRESS OR  \nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
    OF MERCHANTABILITY,  \nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
    NO EVENT SHALL THE  \nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES
    OR OTHER  \nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM,  \nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
    IN  \nTHE SOFTWARE. \n```\n"
notices: []
```

**Comment by pitr-ch** [comment]
I've changed it to txt file and made sure it works in YARD. Will it work for you like this?

**Comment by mikrobi** [comment]
@pitr-ch that looks good to me!

**Pull request merged**
