### PR TITLE
Edge Gem

### PR DESCRIPTION
**Pull request by jdantonio**
## In Progress -- Do Not Merge

### CODE REVIEW

**Comment by pitr-ch** [comment]
Thanks, I'll submit few updates later along with the new Promises work.

**Comment by jdantonio** [comment]
@pitr-ch Cool. Thank you!

I may move `Exchanger` into the edge gem, too. I'm not sure if you've seen the conversation between @chrisseaton and me in #271, but we have a race condition in `Exchanger` that we may not be able to fix easily.

**Comment by pitr-ch** [comment]
@jdantonio yeah, I think it makes sense to move there all things that we are not sure about. We can always easily move them back if needed.

**Comment by pitr-ch** [comment]
Continues in #274

**Comment by jdantonio** [comment]
Merged into #274.

**Pull request closed without merging**
