### PR TITLE
Add `require 'fiber'` for `Fiber.current` usage.

### PR DESCRIPTION
**Pull request by ioquatix**
Fixes <https://github.com/ruby-concurrency/concurrent-ruby/issues/962>.

### CODE REVIEW

**Review by matthewd — APPROVED** [review]
At a quick glance it looks like the prevailing style is to require stdlib before `concurrent/*`, FWIW... though it obviously doesn't matter.

**Comment by ioquatix** [comment]
I think we should also consider moving `Fiber.current` into core ruby.

**Comment by ioquatix** [comment]
https://bugs.ruby-lang.org/issues/19453

**Review by eregon — APPROVED** [review]
Thanks!

**Pull request merged**
