### PR TITLE
Preparing 0.9.2 release

### PR DESCRIPTION
**Pull request by jdantonio**
Removed Java 7 deprecation warning.

### CODE REVIEW

**Comment by jdantonio** [comment]
Addresses #435 

@jrochkind @pitr-ch Thoughts?

**Comment by jrochkind** [comment]
The message works for me. 

But let's think about it. If Rails5 is going to include ruby-concurrent as a Gemfile, and Rails5 is going to officially support Java 7 on Jruby (by way of officially supporting anything Jruby does).... this message means that every time a Rails app starts on Jruby/Java 7, they'll get this message, even though it's supported. In the log of every rake task, possibly in the output of every CI run (depending on logging settings), etc. 

I wonder if a warning is appropriate at all. But I don't understand the implications of using Java 7. 

If a warning is appropriate, this wording seems good.

**Comment by jrochkind** [comment]
Except, actually, if you do want a warning -- "ruby-concurrent" should be included in the warning somehow too, otherwise people may have no idea where the warning is coming from (what is it that's telling them Java 7 is recommended against?), especially when their project only has ruby-concurrent as an indirect dependency (which will be common, cause ruby-concurrent is that kind of thing, that lots of things are going to be depending on).

**Comment by jdantonio** [comment]
Very good point. Rails has a rule that their dependencies cannot display post-install messages. I've asked and they don't have a problem with warnings once the gem loads, so we comply with the proverbial _letter_ of the law. But what about the _spirit_ of the law. In some respects this is a binary value: either we support Java 7 or we don't. And we do. So perhaps we should just remove the warning entirely and leave the suggestion for Java 8 in the README.

**Comment by jrochkind** [comment]
+1

**Comment by ianks** [comment]
So Java 7 will not be deprecated in 1.0?

**Comment by jdantonio** [comment]
@ianks Correct. We will continue to support Java 7.

@jrochkind Time got away from me last weekend so I wasn't able to release this as I had intended. I plan to release it this weekend. I am going to remove the deprecation warning completely, as we discussed, and let the README explain our preference for Java 8.

**Comment by pitr-ch** [comment]
+1 for just README

**Comment by lucasallan** [comment]
:+1:

**Comment by Ch4s3** [comment]
:+1:

**Comment by jdantonio** [comment]
@pitr-ch @soupmatt: The latest commit on this branch cherry-picks @soupmatt's update from PR #457 back to the 0.9.x branch. Please take a look. I'll release 0.9.2 once you've both given a :+1: to the change.

**Comment by pitr-ch** [comment]
looks good, travis did not run though

**Comment by soupmatt** [comment]
Sorry for the late reply. I tested my stuff against this branch and it works.

**Comment by jdantonio** [comment]
@soupmatt No worries. I've been so busy lately that I'm *way* behind on the latest releases. I appreciate you taking the time to test it for us!

**Comment by jdantonio** [comment]
Released.

**Pull request closed without merging**
