### PR TITLE
Promise.zip execution changes

### PR DESCRIPTION
**Pull request by davishmcclurg**
I added details for each change in the commit messages.
Let me know if you'd like these in separate PRs.

### CODE REVIEW

**Comment by pitr-ch** [comment]
Thanks. The change makes sense but as you said it's a breaking change. Could you introduce the non-executing behavior with an option passed to zip?

**Comment by davishmcclurg** [comment]
@pitr-ch I added an `execute` option and switched the default back to returning a fulfilled promise.

**Comment by pitr-ch** [comment]
@davishmcclurg Thanks for the update, looks good. One last think though, could you update the documentation to mention the new option?

**Comment by davishmcclurg** [comment]
@pitr-ch I finally got around to updating the docs. I believe `@overload` was necessary here, but let me know if there's something cleaner.

**Comment by pitr-ch** [comment]
Thanks looks great! I've rebased the PR to pass the CI. When green I'll merge it.

**Pull request merged**
