### PR TITLE
Fix an instance variable clash in Rbx

### PR DESCRIPTION
**Pull request by asppsa**
This is a proposed fix for #367.   Both `Concurrent::Synchronization::RbxObject` and
`Concurrent::Edge::Event` have a `@Waiters` ivar.  The latter class inherits from the former when running under Rubinius, so I've changed the name of the ivar in `RbxObject`.

### CODE REVIEW

**Comment by jdantonio** [comment]
@asppsa Thank you for looking into this! I've looked at your PR and the Edge::Event implementation and I think you are correct. Since this update affects code that @pitr-ch wrote, I'm going to wait for his feedback before merging.

The tests that are failing on AppVeyor are known to fail intermittently and are not related to this PR.

**Comment by pitr-ch** [comment]
Thanks again @asppsa it's merged. 

@jdantonio I think this deserves new release 0.9.1, I think it may be time for me to try the process. Do we have an up to date documentation for that?

**Comment by jdantonio** [comment]
@pitr-ch I agree that this warrants an update.

We don't have a document describing the complete build process. I'll create a to-do for myself to write that documentation.

To create the build you'll need to have both MRI and JRuby installed and configured with the appropriate build tools and libraries. I assume you already have all that. To create the Windows build you'll need to install docker. If you are on OS X you'll also need boot2docker. Once you have all that setup, everything if fairly automated:

* Update`version.rb`
* Update the CHANGELOG
* Switch to MRI
  - Make sure docker is running (otherwise the windows build task will not be available)
  - Run `bundle exec rake clean` to get rid of old artifacts
  - Run `bundle exec rake build` to build core, ext, ext-windows, and edge into the *pkg* directory
* Switch to JRuby
  - Delete *Gemfile.lock* and run `bundle install` (this isn't always necessary, but our multi-gem setup sometimes confuses bundler)
  - Run `bundle exec rake clean` to get rid of old artifacts
  - Run `bundle exec rake build` to build core-java into the *pkg* directory
* If everything looks good, update git
  - Commit the changes
  - Tag the master branch with the version number
  - Push to GitHub
* Update the Yard documentation
  - Run `bundle exec rake yard` to update the documentation
  - Run `bundle exec rake yard:push` to push the docs to GitHub Pages
* For each gem file in *pkg* run `gem push pkg/concurrent-ruby-<...>.gem` to push to Rubygems
* Update the release in GitHub
  - Select the `releases` link on the main repo page
  - Press the `Edit` button to edit the release
  - Name the release based on the version number
  - Add a description
  - Attach all the `*.gem` file
  - Save the updated release

Wow. Now that I've written this all out it's more complicated than I realized. I guess it just seems easier since I've done it so many times! There is definitely an opportunity for more automation.

In the `rake-compiler-dev-box` repo there is additional automation for testing the produced `*.gem` files. Those tests require Vagrant and a configured virtual machine. It's not worth your time to run those tests right now. This PR hasn't changed anything that could cause a problem. Now that we're using Docker I want to move those tests into the main project and deprecate that repo.

Thank you for taking the time to learn the build process! Let me know if you have any problems.

**Comment by jdantonio** [comment]
@pitr-ch Do you still want to handle the 0.9.1 release? If so, when do you think you will create the release?

**Comment by pitr-ch** [comment]
@jdantonio yes, thanks for the detailed description. I'll do it this weekend.

**Comment by jdantonio** [comment]
When I try to build the Windows gems on my OS X system I get an error. I have to run the following command manually:

> rake-compiler-dock bash -c "gem install bundler && bundle install && rake cross native gem RUBY_CC_VERSION=1.9.3:2.0.0:2.1.6:2.2.2 && rm -rf .bundle"

This is a reminder to myself to follow-up with the author of `rake-compiler-dock`.

**Comment by larskanis** [comment]
@jdantonio Which error did you get with rake-compiler-dock (just stumbled accross your comment) ?

**Comment by jdantonio** [comment]
@larskanis I'm traveling for work on right now any my notes are on my home computer. I'll send you detailed info soon (hopefully this weekend).

**Comment by larskanis** [comment]
OK. Feel free to open an issue on rake-compiler-dock.

**Pull request merged**
