### PR TITLE
Synchronization updates

### PR DESCRIPTION
**Pull request by pitr-ch**
Work in progress, todo:
- [ ] update documentation
- [x] fix JRuby
- [ ] tests
- [x] safe_initialization!
- [x] Java 7 support

### CODE REVIEW

**Comment by jdantonio** [comment]
Looks great so far! Any idea when this will be ready to merge?

**Comment by pitr-ch** [comment]
Unless I run into issues, it should be merged in few days.

**Comment by pitr-ch** [comment]
I am doing one more biggish change around `ensure_ivar_visibility!`. It will be hidden behind a class inheritable flag `safe_initialisation`! Advantages are: easier for users to track, it's no longer in initialise; it only called once, no more duplications; it's called only when truly needed. I should have it done on weekend.

**Comment by pitr-ch** [comment]
Notes:
- requires Fences of Java 8
- will enforce `@FinalIvar` convention to make it testable that classes using it are marked with `safe_initialization!`

**Comment by jdantonio** [comment]
We cannot require Java 8. As discussed [here](https://github.com/ruby-concurrency/concurrent-ruby/pull/386#issuecomment-130289441), JRuby 9000 supports both Java 7 and Java 8. That's why we are still using the internal implementation of ConcurrentHashMap (imported from thread_safe) rather than the Java 8 implementation.

**Comment by pitr-ch** [comment]
This is related to conversation in https://github.com/ruby-concurrency/concurrent-ruby/pull/357 too. I was remembering it wrong and I thought we are going to drop Java 8 support. I'll put the "best effort" hack for java 7 back and I'll keep working on this after rc.

@jdantonio sorry that it takes so long.

**Comment by jdantonio** [comment]
At one point we talked about dropping Java 7 support but then Rails happened and @thedarkone reminded us of the need to support Java 7.

**Comment by jdantonio** [comment]
I've added the two tests that failed to my list of buggy tests. They aren't related to this PR.

@pitr-ch Is this ready to merge? The docs aren't necessary for a pre-release.

**Comment by pitr-ch** [comment]
Ok, I'll check the bug on travis, and I'll merge today.

**Comment by jdantonio** [comment]
Cool. Once that's done I'll create the next pre-release and submit the thread_safe replacement PR to Rails. Thank you!

**Comment by pitr-ch** [comment]
@jdantonio Thanks for your patience.

**Comment by jdantonio** [comment]
I've published a new pre-release and submit the PR to Rails which replaced thread_safe. That PR was merged. My priorities for 1.0 are interpreter warnings, buggy tests, and documentation. None of that will get in the way of your continued work on synchronization.

We're almost there! :-)

**Comment by pitr-ch** [comment]
Thank you! I'll focus now on the documentation for the layer.

**Pull request merged**
