### PR TITLE
Use latest version of rake-compiler

### PR DESCRIPTION
**Pull request by prashantvithani**
The latest version of rake-compiler has fixed the issue with java classpath. Refer: https://github.com/rake-compiler/rake-compiler/pull/147

### CODE REVIEW

**Comment by pitr-ch** [comment]
Thanks, unfortunately I am cross compiling (building the java extension using mri) and looking at the change in the linked issue, it is actually the cause why it broke for me and why added the monkey patch to fix it quickly. Without the  https://github.com/rake-compiler/rake-compiler/pull/147 it was possible to set JRUBY_HOME it would work fine. Now it only uses `RbConfig::CONFIG['libdir']` which is obviously wrong when executing the rake task on MRI.

**Comment by prashantvithani** [comment]
Oh, I certainly didn't think of cross-compilation while changing it to `RbConfig::CONFIG['libdir']`. Thanks for pointing this out. Can you mention the reproduction steps? It'll be easier to fix if I know the exact scenario.

**Comment by pitr-ch** [comment]
It fails when `bundle execute rake lib/concurrent/concurrent_ruby.jar` is executed on MRI. Th jruby.jar path ends up to be `/usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/jruby.jar` which can be seen in the output of the command, look for `javac  -target 1.6 -source 1.6 -Xlint:unchecked  -cp "/usr/local/Cellar/rbenv/1.1.1/versions/2.5.1/lib/jruby.jar:" ...`. Thanks.

**Comment by pitr-ch** [comment]
https://github.com/ruby-concurrency/concurrent-ruby/pull/783/commits/ad6555cffd43a5073f3a6bc1e013c64d50f9d606 might be helpful.

**Comment by prashantvithani** [comment]
@pitr-ch Thanks for suggestion :). I'll try to fix the upstream issue this weekend.

**Comment by prashantvithani** [comment]
@pitr-ch Quite late, but I've raised PR fixing this in rake-compiler/rake-compiler#151.

**Comment by prashantvithani** [comment]
@pitr-ch I've updated the PR

**Comment by pitr-ch** [comment]
@prashantvithani thank you for your help and contributions, I've took your changes and used them in my [branch](https://github.com/ruby-concurrency/concurrent-ruby/pull/791/commits/bb99e88b10c4faf3aabb236f46d7ab90d6ff4a89). The cross compilation of JRuby now works perfectly 👍

**Pull request closed without merging**
