### PR TITLE
Allow root promise body to be set later

### PR DESCRIPTION
**Pull request by pitr-ch**
Comments, suggestions? 

Please do not merge, testing with Dynflow first.

### CODE REVIEW

**Comment by pitr-ch** [comment]
cc @iNecas

**Comment by jdantonio** [comment]
Has anyone experimented with having `Promise` extend `IVar` the way `Future` does? I glanced at the code the other day and it looked like Promise has internal methods very similar to the state-setting methods of IVar. I haven't had a chance to work with the code yet but it seemed like a potential approach.

**Comment by jdantonio** [comment]
@pitr-ch @iNecas Please see #270.

**Comment by pitr-ch** [comment]
closing in favor of #270

**Pull request closed without merging**
