### PR TITLE
Adding dynamic thread pool executor length setters

### PR DESCRIPTION
**Pull request by thomas07vt**
- Adding ability to change the thread pool executor @min_length and 
  @max_length variables at runtime
- Removed unnecessary attr_readers, is there a reason why we need them?

- Use case: Spin up new threads dynamically when higher throughput is
  required
- Use case: Spin down threads dynamically to reduce server load

- Question: The initializer options use :max_threads and :min_threads,
  however the current attr_readers are :max_length and :min_length so I
  set up the getters and setters to use the existing terminology. Would
  it be useful to name the getters and setters #max_threads=() and
  #min_threads=()?

### CODE REVIEW

**Comment by pitr-ch** [comment]
Thanks! I have to have a careful look, I'll get back to it after 1.0.3 is out.

The naming is unfortunate, and omission on our part that we did not notice it. I would choose max/min threads, the other one should be just alias and deprecated. Would you be so king and contribute fix for it as well?

**Comment by thomas07vt** [comment]
Yep, ill work on the alias/deprecation later today

**Comment by thomas07vt** [comment]
@pitr-ch 

- Changed min_length and max_length references to be min_threads and
  max_threads. This is to be consistent with the initializer options

- Deprecated the min_length and max_length methods. I used the same
  method that I found in lib/concurrent/edge/future.rb:564 is the that
  desired way?

- I didn't add macro commands on the deprecated methods. I actually
  don't really know what the macro commands do at all :) . Please let me
  know if you would like for me to change them

**Comment by jdantonio** [comment]
The macros are for documentation. Many of our classes share APIs and I didn't want to write the same text over and over. Don't worry about them They are finicky and hard to get write (our documentation is complex).

**Comment by pitr-ch** [comment]
John @thomas07vt Thank a lot for your help. It looks perfect. The macros are as @jdantonio said, it's a YARD's macro system. I'll update it when I'll pull the PR for local review.

**Comment by thomas07vt** [comment]
Just following up with this PR, @pitr-ch have you been able to do a local review of this PR? Anything you think I should change/improve?

**Comment by pitr-ch** [comment]
Now after 1.0.3 release I'll start revisiting postponed issues and PRs to 1.0.4 including this one. I'll be getting to it soon. Thanks and sorry that it takes time.

**Comment by thomas07vt** [comment]
No rush, just wanted to follow up to see if you had anymore comments!

**Comment by pitr-ch** [comment]
Hi @thomas07vt, sorry that it took me so long to get to this PR. I plan to release this in 1.1 since it adds new methods. I've pushed one minor fix and documentation (including macros) update.

However I've noticed that there are other methods like `largest_length` and `length`. So they can either also be updated to `largest_thread_count` and `thread_count` (or similar names) which would increase the API change. I think we rather should take back the `min/max_length` renaming and fix just the option names. Sorry for giving bad advise about the names before, I'll rollback the renaming.

**Comment by thomas07vt** [comment]
Sounds good @pitr-ch ... let me know if you need anything else from me.

**Comment by chrisseaton** [comment]
@thomas07vt are you still interested in working on this issue? I know it's been a very long time.

**Comment by chrisseaton** [comment]
I'm going to close this due to extreme age. That doesn't mean we're opposed to the idea, please re-engage with us if you want to.

**Comment by brauliobo** [comment]
I'm looking forward to this feature

**Comment by chrisseaton** [comment]
Thanks I'll wait out to see if there's more interest from other people.

**Pull request closed without merging**
