### PR TITLE
Actors - Improving documentation; other improvements

### LINKED ISSUE #155: Documentation on Actors is misleading
On http://ruby-concurrency.github.io/concurrent-ruby/Concurrent/Actor.html (as linked from https://github.com/ruby-concurrency/concurrent-ruby#features--documentation) the code samples use a `terminated` method on the actor which does not exist on 0.7.0.

The Wiki mentions (https://github.com/ruby-concurrency/concurrent-ruby/wiki#asynchronous-concurrency) which links to a different page in the docs (http://ruby-concurrency.github.io/concurrent-ruby/Concurrent/Actress.html):

>  Actress (replacement for the deprecated Actor)

It would be nice if the documentation could somehow reflect reality a bit better.

### PR DESCRIPTION
**Pull request by pitr-ch**
fixes #155

### CODE REVIEW

**Comment by pitr-ch** [comment]
I'll probably show few new thinks I am cooking in actors on FOSDEM but it'll not make it to 0.8 :(

**Comment by jdantonio** [comment]
No hurry. I just want to make sure I don't push releases without giving you the opportunity to merge.

**Comment by pitr-ch** [comment]
@jdantonio I hope I'll update this PR after this weekend but still it won't be ready for merge unless we mark it experimental (probably not a good idea). This may interest you though, after looking more into Akka and Erlang supervision approach I am moving more towards Erlang's approach so next version will have Erlang's behavior (with minor changes since this is OOP) and its Supervisor implemented. It would be great if you could review it after it's ready since you have experience with Erlang.

**Comment by jdantonio** [comment]
Absolutely! I'm looking forward to seeing what you put together.

**Comment by Papipo** [comment]
@pitr-ch are the interfaces going to change?

**Comment by pitr-ch** [comment]
@Papipo Unfortunately there will be some changes, nothing fundamental though.

**Comment by jdantonio** [comment]
@pitr-ch Is work on this PR still ongoing, or has it been superseded by other PRs?

**Comment by pitr-ch** [comment]
Ongoing, This will be merged to #274 and merged with it, I'll close this one then.

**Comment by pitr-ch** [comment]
This is updated and will be merged after #296.

**Comment by pitr-ch** [comment]
Ready for merge.

**Pull request merged**
