### PR TITLE
Fix `Promise#then`.

### PR DESCRIPTION
**Pull request by reitermarkus**
The docs say it should work like `then(executor: executor)`.

### CODE REVIEW

**Comment by pitr-ch** [comment]
Hi, thanks for the fix. However the docs need to be fixed instead at the moment. The change as is would be backward incompatible. (Even though I would also like to use named arguments.)

**Comment by reitermarkus** [comment]
Maybe we could support both in order to not break compatibility?

**Comment by pitr-ch** [comment]
yeah, that's a good plan, however concurrent-ruby has to drop support for 1.9 officially first to be able to do it. So I won't be able to merge this PR until before next minor release.

**Comment by reitermarkus** [comment]
> concurrent-ruby has to drop support for 1.9 officially first

Why? There are other methods using named parameters.

**Comment by reitermarkus** [comment]
@pitr-ch, ping.

**Comment by pitr-ch** [comment]
Sorry I was away. I think they are using last argument as an options Hash, named arguments should not be used. If you saw named arguments please point me to it.

**Comment by reitermarkus** [comment]
> I think they are using last argument as an options Hash

Yes, I just meant that they can be used with named parameters, not that they are implemented with them.

Anyways, I implemented it to support both the current and the version with an option Hash.

**Pull request merged**
