### PR TITLE
add timeoutable method for run futures with timeout

### PR DESCRIPTION
**Pull request by fntz**
Hi,
I add a new method for work with `future` and timeout.

### CODE REVIEW

**Comment by jdantonio** [comment]
@fntz Thank you very much for taking the time to work on this. I greatly appreciate your effort. Unfortunately I cannot accept this PR. It violates a couple strict rules for this gem. I apologize that these rules aren't documented well. The next time I work on documentation I will make these rules clear. The two issues are:

1. **No downstream dependencies.** This gem is intended to be a core library for a wide range of frameworks and applications. Downstream dependencies limit our ability to control the effect we have on the projects that use us. One of the reasons that projects like Rails and Sidekiq have chosen to use concurrent-ruby is my commitment to this ideal.
2. **Never monkey-patch Ruby.** Basically for the reasons stated above. The `timeout` gem is pretty abusive to both `Thread` and `Kernel`. Monkey-patching like that wouldn't just affect the code within this gem, it would transitively affect the application which uses c-r and *every* one of its downstream dependencies. This would pose significant risk for our users.

Those issues aside, I am fairly opposed to adding a `timeout` method to c-r. Timeout is very complex, problematic, and is best handled by the application itself. This has been [discussed here before](https://github.com/ruby-concurrency/concurrent-ruby/pull/285#commitcomment-11217248). In fact, I *removed* an earlier `timeout` implementation for these reasons (I should blog about this sometime). I recommend reading Mike Perham's ["Timeout: Ruby's Most Dangerous API"](http://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/) and Charlie Nutter's ["Ruby's Thread#raise, Thread#kill, timeout.rb, and net/protocol.rb libraries are broken"](http://blog.headius.com/2008/02/ruby-threadraise-threadkill-timeoutrb.html) for more context.

**Comment by fntz** [comment]
ok, thanks for reply.

**Comment by pitr-ch** [comment]
@fntz I am curious, what lead you to add this API, why was not `Future#value(timeout)` not sufficient ?

**Comment by fntz** [comment]
@pitr-ch i think `Future#value` non async and block current thread (from my view of course and java experience :)).

**Comment by pitr-ch** [comment]
So you wanted to be able to build a job which runs at most `x` seconds in background. For that the job has to be safely cancel-able which we plan to tackle in next major release.

**Comment by fntz** [comment]
ok, this fine for me. many thanks.

**Pull request closed without merging**
