### PR TITLE
Cleanup GitHub Actions workflow

### PR DESCRIPTION
**Pull request by eregon**
* No need to install Bundler a second time, it was also unused.
* JAVA_OPTS are already shown in the log.

### CODE REVIEW

**Comment by chrisseaton** [comment]
These are all existing failures aren't they? We need to get on top of this...

**Review by chrisseaton — APPROVED** [review]

**Comment by chrisseaton** [comment]
Can you please rebase?

**Comment by chrisseaton** [comment]
@eregon can you rebase?

**Comment by eregon** [comment]
Rebased, let's check if the CI is still happy, should be since it's only cleanups.

**Pull request merged**
