### PR TITLE
Fix Array/Hash/Set construction broken on TruffleRuby

### PR DESCRIPTION
**Pull request by ivoanjo**
While trying to get the [Persistent-💎](https://gitlab.com/ivoanjo/persistent-dmnd) gem specs to work on TruffleRuby, I discovered that Array/Hash/Set construction was broken in several cases.

I've added test cases for the expected behaviors of Array/Hash/Set `.[]` and `.new`, and fixed a number of broken test cases on TruffleRuby (all specs are green on MRI).

There is one remaining spec in `array_spec.rb` that was already broken and that is non-trivial to fix, so I'll create an issue for it.

### CODE REVIEW

**Comment by eregon** [comment]
@pitr-ch Please take a look :)

**Comment by pitr-ch** [comment]
Thanks @ivoanjo for the fix and the tests! I'll have a in depth look soon.

**Comment by pitr-ch** [comment]
I've updated the PR with a different solution which I've already had locally. It should be simpler since it is not needed to look up all the Array and Hash methods which create new instance with a special behavior without initialize, allocate, etc.

**Comment by ivoanjo** [comment]
Nice! I also think the previous approach was rather brittle and could easily break in newer versions.

Let me know if I can help with anything else! TruffleRuby without concurrent-ruby is like going to Disneyland on a rainy day ;)

**Pull request merged**
