### PR TITLE
CI: Add Ruby 2.6.0 to matrix

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR adds latest MRI to the matrix.

  - remove 2.6.0-rc1

### CODE REVIEW

**Comment by pitr-ch** [comment]
Thanks.  
```
     - name: MRI 2.5.1
       rvm: 2.5.1	     
```
The above should be added so we keep testing all minor versions.

**Comment by pitr-ch** [comment]
Do you know why the 1.9.3 is running so old bundler? 1.17.3 bundler still supports 1.9.3.

**Comment by olleolleolle** [comment]
@pitr-ch We can add a `before_install` to 1.9.3's matrix item, and do a `gem install bundler` there.

**Comment by olleolleolle** [comment]
@pitr-ch I added 2.5, and also a before_install for 1.9.3.

**Pull request merged**
