### PR TITLE
Future, Actor improvements

### PR DESCRIPTION
**Pull request by pitr-ch**
please see commit messages

### CODE REVIEW

**Comment by jdantonio** [comment]
@pitr-ch Is this ready to merge, or is it waiting until after I release 0.9.0?

**Comment by sschepens** [comment]
@jdantonio @pitr-ch I would love this to be in a release, I have tested locally and seems to work.
Anyway, this affects only concurrent-edge so could be release separately from 0.9.0

**Comment by pitr-ch** [comment]
As @sschepens said, I've planned it for separate edge release, but we could get it in 0.9. I'll just update documentation and merge today.

**Comment by pitr-ch** [comment]
cc @iNecas

**Comment by iNecas** [comment]
Will check in an hour


On čt, VII 9, 2015 at 9:49 dop., Petr Chalupa <notifications@github.com>
wrote:

cc @iNecas <https://github.com/iNecas>


—
Reply to this email directly or view it on GitHub
<https://github.com/ruby-concurrency/concurrent-ruby/pull/363#issuecomment-119860242>
.

**Comment by iNecas** [comment]
works for me

**Comment by jdantonio** [comment]
@pitr-ch Since the 0.9.0 release will move several classes out of core and into edge, I think we need a full release of edge at the same time. Once we have a 0.1.0 release of edge I think we can release it separately. But I don't think we should release core 0.9.0 while edge is still in pre-release.

Thank you for jumping on this!

**Comment by pitr-ch** [comment]
@jdantonio completely agree, I meant a next release after the first one companioning 0.9 core.

**Pull request merged**
