### PR TITLE
Add CI-tests on Windows.

### PR DESCRIPTION
**Pull request by larskanis**
The github repository is not yet enabled for CI-tests on appveyor. This can be done by adding concurrent-ruby as a new project on http://appveyor.com .

The SVG image URL must be replaced by the one of the owner the ruby-concurrency account - it shows the status for my repository, currently.

I did not enable all possible Ruby targets, because appveyor is slow...

In theory all tests should pass, but there are some timing dependent specs, that seems to fail like [here](https://ci.appveyor.com/project/larskanis/concurrent-ruby)

### CODE REVIEW

**Comment by ianks** [comment]
Do appveyor builds run concurrently?

**Comment by larskanis** [comment]
Not on the free accounts.

**Comment by nirvdrum** [comment]
For anyone else confused, it looks like the correct URL is http://www.appveyor.com/.

**Comment by larskanis** [comment]
Yes, its .com, sorry!

**Comment by jdantonio** [comment]
I didn't know that AppVeyor existed, so thank you @larskanis for the info. I've started experimenting with it over [here](https://ci.appveyor.com/project/jdantonio/concurrent-ruby) using PR #361. If it works as expected I'll integrate once I've looked over and merged #359.

**Comment by jdantonio** [comment]
I created an AppVeyor account for the `ruby-concurrency` org and configured the necessary webhook. I also manually ran a job against @larskanis fork. It seems to [work very well](https://ci.appveyor.com/project/rubyconcurrency/concurrent-ruby). Unfortunately AppVeyor drops the dash from "ruby-concurrency" when it creates the org URL, so the org path is "rubyconcurrency."

I expect to merge this later this evening, once I've left work.

**Comment by ianks** [comment]
Should we set an environment variable to prevent Appveyor from using Coveralls?

**Comment by jdantonio** [comment]
We can. I'm fairly ambivalent, to be honest. I've given up on Coveralls for this gem. I removed the badge from the README. Because of the platform-specific code our test coverage reports are always artificially low. Until we can figure out how to get a more accurate coverage score out of Coveralls, it doesn't have much more value than simply running the tests locally using simplecov.

**Comment by jdantonio** [comment]
@larskanis My Internet access is down because my provider sent me new, faulty equipment. I only have my phone right now. I'll work on this as soon as I get my Internet issue resolved.

**Comment by larskanis** [comment]
@jdantonio My internet provider took me offline for almost half a year. I'll keep my fingers crossed and hope that your issue will be solved faster...

**Pull request merged**
