### PR TITLE
Parallel Enumerable

### PR DESCRIPTION
**Pull request by SebastianEdwards**
Opening a pull-request so we can continue discussions on this feature.

### CODE REVIEW

**Comment by pitr-ch** [comment]
@SebastianEdwards thanks!

**Comment by jdantonio** [comment]
@SebastianEdwards Now that I've released 0.8.0 you may want to consider rebasing this branch. There are a ton of commits in that release. It certainly isn't necessary, but if you do a normal merge your commits may be buried in a sea of C/Java extension related commits.

**Comment by SebastianEdwards** [comment]
git rebasing:

rebasing

**Comment by jdantonio** [comment]
@SebastianEdwards Do you mind giving me commit access to your fork?

**Comment by SebastianEdwards** [comment]
@jdantonio Not at all, added you are a collaborator now

**Comment by jdantonio** [comment]
Well, I messed that up. I thought you had created the PR between your `parallel` branch and the main repo's `master` branch. I'm going to create a new PR for us to continue this discussion.

**Comment by jdantonio** [comment]
Move to PR #231

**Pull request merged**
