### PR TITLE
Added bundler cache for faster builds

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by pitr-ch** [comment]
Since we do not have Gemfile.lock committed when does the cache updates?

**Comment by thedrow** [comment]
That's a good question. Let's commit again and see if it speeds up the build.

**Comment by pitr-ch** [comment]
Where do you mean to commit again?

**Comment by thedrow** [comment]
I'll do it today.

**Comment by jdantonio** [comment]
@thedrow Thank you very much for the submission. If this speeds up the build we'll definitely merge it in.

**Comment by thedrow** [comment]
Looks like Travis is adding a vendor path automatically if you don't override the default installation instructions which we didn't.
For Ruby 2.2 the difference is between ~15 seconds to 4.26s.

**Comment by thedrow** [comment]
Total time is 1 hr 6 min 13 sec instead of ~1 hr and 30 minutes.

**Comment by pitr-ch** [comment]
Thank you, that looks quite promising. However I did not find how the cache is updated in the travis documentation. Do you know how does it behave? When the cache is updated?

**Comment by thedrow** [comment]
@pitr-ch They have two mechanisms. One uses md5 and the other checks if the mtime of any of the files is different.
The latter is inaccurate and will cause cache invalidation often but they are phasing it out.

**Comment by pitr-ch** [comment]
Thanks @thedrow, so lets try it 👍

**Comment by Taher-Ghaleb** [comment]
Hello,

Sorry, I know it's been a long time ago, but I am curious why caching hasn't been enabled before this (i.e., since December 17, 2014, when it became available to open source projects).

Thank you.

**Pull request merged**
