### PR TITLE
Resolved NameError on JRuby by using fewer autoloads.

### PR DESCRIPTION
**Pull request by jdantonio**
See issue #480.

### CODE REVIEW

**Comment by jdantonio** [comment]
@pitr-ch Can you do a quick code review run some local tests against this, please? I want to make sure there aren't any unintended bugs created by this.

I'll pull the latest Rails code and run its tests agains this branch to verify I haven't broken anything there and that we aren't generating warnings.

Here are the shell commands I ran to spot check this:

```
be ruby -w -e "require 'concurrent/future'; Concurrent::Future.execute { puts 'Boom' }"
be ruby -w -e "require 'concurrent/promise'; Concurrent::Promise.execute { puts 'Boom' }"
be ruby -w -e "require 'concurrent/scheduled_task'; Concurrent::ScheduledTask.execute(0.1) { puts 'Boom' }"
```

**Comment by schneems** [comment]
Could we introduce some integration style tests for something like this? Small scripts that use different parts of this gem that we can call via Process.spawn and assert success or output perhaps?

**Comment by jdantonio** [comment]
That's a very good idea. I have a set of scripts in the `build-tests` directory that I run whenever a create a new release. I have to manually watch them run and verify the results. I really need to automate those, too. I'll work on that as soon as I can.

**Comment by schneems** [comment]
I do it all the time. Here's an example in Puma Worker Killer https://github.com/schneems/puma_worker_killer/blob/9be33d056d86f8bd312b815f30395934dee3d500/test/puma_worker_killer_test.rb#L9

**Pull request merged**
